//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbiad.App.DataAccess.Meyesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYS_FOLLOWINFO
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long OpponentUserId { get; set; }
        public bool IsActive { get; set; }
        public int StartDate { get; set; }
        public int StartTime { get; set; }
        public int EndDate { get; set; }
        public int EndTime { get; set; }
    }
}
