//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbiad.App.DataAccess.Meyesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYS_MESSAGE
    {
        public long Id { get; set; }
        public short Status { get; set; }
        public long UserId { get; set; }
        public int EntryDate { get; set; }
        public int EntryTime { get; set; }
        public string Message { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public string MediaType { get; set; }
        public string Media { get; set; }
    }
}
