//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbiad.App.DataAccess.Meyesos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYS_USER
    {
        public long Id { get; set; }
        public short Status { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string PersonalMessage { get; set; }
        public int BirthDate { get; set; }
    }
}
